// Sahibinden.com scraper konfigürasyonu
// city_id = Türkiye plaka kodları (sahibinden bunları kullanır)

const ILLER = [
  { id: 1,  ad: 'Adana',          slug: 'adana' },
  { id: 2,  ad: 'Adıyaman',       slug: 'adiyaman' },
  { id: 3,  ad: 'Afyonkarahisar', slug: 'afyonkarahisar' },
  { id: 4,  ad: 'Ağrı',           slug: 'agri' },
  { id: 5,  ad: 'Amasya',         slug: 'amasya' },
  { id: 6,  ad: 'Ankara',         slug: 'ankara' },
  { id: 7,  ad: 'Antalya',        slug: 'antalya' },
  { id: 8,  ad: 'Artvin',         slug: 'artvin' },
  { id: 9,  ad: 'Aydın',          slug: 'aydin' },
  { id: 10, ad: 'Balıkesir',      slug: 'balikesir' },
  { id: 11, ad: 'Bilecik',        slug: 'bilecik' },
  { id: 12, ad: 'Bingöl',         slug: 'bingol' },
  { id: 13, ad: 'Bitlis',         slug: 'bitlis' },
  { id: 14, ad: 'Bolu',           slug: 'bolu' },
  { id: 15, ad: 'Burdur',         slug: 'burdur' },
  { id: 16, ad: 'Bursa',          slug: 'bursa' },
  { id: 17, ad: 'Çanakkale',      slug: 'canakkale' },
  { id: 18, ad: 'Çankırı',        slug: 'cankiri' },
  { id: 19, ad: 'Çorum',          slug: 'corum' },
  { id: 20, ad: 'Denizli',        slug: 'denizli' },
  { id: 21, ad: 'Diyarbakır',     slug: 'diyarbakir' },
  { id: 22, ad: 'Edirne',         slug: 'edirne' },
  { id: 23, ad: 'Elazığ',         slug: 'elazig' },
  { id: 24, ad: 'Erzincan',       slug: 'erzincan' },
  { id: 25, ad: 'Erzurum',        slug: 'erzurum' },
  { id: 26, ad: 'Eskişehir',      slug: 'eskisehir' },
  { id: 27, ad: 'Gaziantep',      slug: 'gaziantep' },
  { id: 28, ad: 'Giresun',        slug: 'giresun' },
  { id: 29, ad: 'Gümüşhane',      slug: 'gumushane' },
  { id: 30, ad: 'Hakkari',        slug: 'hakkari' },
  { id: 31, ad: 'Hatay',          slug: 'hatay' },
  { id: 32, ad: 'Isparta',        slug: 'isparta' },
  { id: 33, ad: 'Mersin',         slug: 'mersin' },
  { id: 34, ad: 'İstanbul',       slug: 'istanbul' },
  { id: 35, ad: 'İzmir',          slug: 'izmir' },
  { id: 36, ad: 'Kars',           slug: 'kars' },
  { id: 37, ad: 'Kastamonu',      slug: 'kastamonu' },
  { id: 38, ad: 'Kayseri',        slug: 'kayseri' },
  { id: 39, ad: 'Kırklareli',     slug: 'kirklareli' },
  { id: 40, ad: 'Kırşehir',       slug: 'kirsehir' },
  { id: 41, ad: 'Kocaeli',        slug: 'kocaeli' },
  { id: 42, ad: 'Konya',          slug: 'konya' },
  { id: 43, ad: 'Kütahya',        slug: 'kutahya' },
  { id: 44, ad: 'Malatya',        slug: 'malatya' },
  { id: 45, ad: 'Manisa',         slug: 'manisa' },
  { id: 46, ad: 'Kahramanmaraş',  slug: 'kahramanmaras' },
  { id: 47, ad: 'Mardin',         slug: 'mardin' },
  { id: 48, ad: 'Muğla',          slug: 'mugla' },
  { id: 49, ad: 'Muş',            slug: 'mus' },
  { id: 50, ad: 'Nevşehir',       slug: 'nevsehir' },
  { id: 51, ad: 'Niğde',          slug: 'nigde' },
  { id: 52, ad: 'Ordu',           slug: 'ordu' },
  { id: 53, ad: 'Rize',           slug: 'rize' },
  { id: 54, ad: 'Sakarya',        slug: 'sakarya' },
  { id: 55, ad: 'Samsun',         slug: 'samsun' },
  { id: 56, ad: 'Siirt',          slug: 'siirt' },
  { id: 57, ad: 'Sinop',          slug: 'sinop' },
  { id: 58, ad: 'Sivas',          slug: 'sivas' },
  { id: 59, ad: 'Tekirdağ',       slug: 'tekirdag' },
  { id: 60, ad: 'Tokat',          slug: 'tokat' },
  { id: 61, ad: 'Trabzon',        slug: 'trabzon' },
  { id: 62, ad: 'Tunceli',        slug: 'tunceli' },
  { id: 63, ad: 'Şanlıurfa',      slug: 'sanliurfa' },
  { id: 64, ad: 'Uşak',           slug: 'usak' },
  { id: 65, ad: 'Van',            slug: 'van' },
  { id: 66, ad: 'Yozgat',         slug: 'yozgat' },
  { id: 67, ad: 'Zonguldak',      slug: 'zonguldak' },
  { id: 68, ad: 'Aksaray',        slug: 'aksaray' },
  { id: 69, ad: 'Bayburt',        slug: 'bayburt' },
  { id: 70, ad: 'Karaman',        slug: 'karaman' },
  { id: 71, ad: 'Kırıkkale',      slug: 'kirikkale' },
  { id: 72, ad: 'Batman',         slug: 'batman' },
  { id: 73, ad: 'Şırnak',         slug: 'sirnak' },
  { id: 74, ad: 'Bartın',         slug: 'bartin' },
  { id: 75, ad: 'Ardahan',        slug: 'ardahan' },
  { id: 76, ad: 'Iğdır',          slug: 'igdir' },
  { id: 77, ad: 'Yalova',         slug: 'yalova' },
  { id: 78, ad: 'Karabük',        slug: 'karabuk' },
  { id: 79, ad: 'Kilis',          slug: 'kilis' },
  { id: 80, ad: 'Osmaniye',       slug: 'osmaniye' },
  { id: 81, ad: 'Düzce',          slug: 'duzce' },
];

const SAHIBINDEN = {
  BASE_URL: 'https://www.sahibinden.com',
  // Satılık daire kategori URL'i - test sırasında doğrulanmalı
  CATEGORY_PATH: '/satilik-daire',
  // Sayfa başına ilan sayısı (sahibinden default: 20)
  PAGE_SIZE: 20,
  DELAY_MIN: 8000,
  DELAY_MAX: 18000,
  // Aynı IP'den çok fazla istek gelirse timeout artar
  REQUEST_TIMEOUT: 30000,
  // Login sayfası
  LOGIN_URL: 'https://www.sahibinden.com/login',
  // Cookie dosyası
  COOKIE_FILE: './cookies/sahibinden.json',
};

const DB_PATH = './data/sahibinden.db';

module.exports = { ILLER, SAHIBINDEN, DB_PATH };
